DEFAULT_BASE_RATE: float = 0.5
DEFAULT_PRIOR_WEIGHT: float = 2.0
DEFAULT_DECAY_HALF_LIFE: float = 86400.0  # 24 hours in seconds
DEFAULT_TRUST_THRESHOLD: float = 0.5
DEFAULT_MIN_UNCERTAINTY: float = 0.01
