from __future__ import annotations

from typing import Protocol, runtime_checkable

from multitrust.core.trust_record import TrustRecord


@runtime_checkable
class TrustStore(Protocol):
    async def get(self, agent_id: str) -> TrustRecord | None: ...
    async def put(self, record: TrustRecord) -> None: ...
    async def delete(self, agent_id: str) -> bool: ...
    async def list_agents(self) -> list[str]: ...
    async def exists(self, agent_id: str) -> bool: ...
    async def close(self) -> None: ...
